[package]
name = "rebag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosbag = { path = "src/rosbag-rs" }
byteorder = "1.1"
tabled = "0.16.0"
ratatui = "0.29.0"
crossterm = "0.28.1"
